# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}

    steps:
      - uses: actions/checkout@v4

      - name: List Files
        run: |
          ls -alh Five  # 列出 Five 目录中的文件，确认 DESCRIPTION 存在

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R/
          key: ${{ runner.os }}-R-${{ hashFiles('Five/**/DESCRIPTION') }}  # 更新路径以匹配您的包
          restore-keys: |
            ${{ runner.os }}-R-

      - uses: r-lib/actions/setup-r@v2
 
