name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: macos-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 列出根目录的文件
      - name: List Root Directory
        run: |
          ls -alh  

      # 安装指定版本的 R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'  
          use-public-rspm: true

      # 安装 Pandoc
      - name: Install Pandoc
        run: |
          brew install pandoc

      # 安装包依赖
      - name: Install Dependencies
        run: |
          cd Five
          Rscript -e "install.packages(c('remotes', 'devtools'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'always')"

      # 检查 R 包
      - name: Check Package
        run: |
          cd Five
          Rscript -e "devtools::check()"

      # 上传测试快照
      - name: Check R Package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          # 指定工作目录，以确保它能找到 DESCRIPTION 文件
          working-directory: Five
