name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: macos-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v4

      - name: List Files in the Package Directory
        run: |
          ls -alh Five  # List files in the Five directory to confirm DESCRIPTION exists

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R/
          key: ${{ runner.os }}-R-${{ hashFiles('Five/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install Dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'always')"

      - name: Check Package
        run: |
          cd Five  # Change directory to the package directory
          Rscript -e "devtools::check()"  # Check package

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
